[project]
name = "ogrodjepisnik"
version = "0.1.0"
description = "A subtitler service for Ogrodje and more"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "openai>=1.84.0",
]
